In [2]:
import numpy as np
import torch

In [2]:
x = torch.Tensor(2, 3)
x

tensor([[5.1395e+31, 3.3132e-18, 6.2611e+22],
        [4.7428e+30, 7.0975e+22, 5.1394e+31]])

In [3]:
y = torch.rand(2, 3)
y

tensor([[0.8102, 0.6974, 0.2740],
        [0.0843, 0.3035, 0.4816]])

In [5]:
a = np.array([1, 2, 3])

In [6]:
v = torch.from_numpy(a)
v

tensor([1, 2, 3])

In [7]:
b = v.numpy()
b

array([1, 2, 3])

In [8]:
b[1] = -1

In [9]:
b

array([ 1, -1,  3])

In [10]:
a

array([ 1, -1,  3])

In [11]:
x = torch.randn(2, 3)

In [12]:
x.view(6)

tensor([-0.7071, -1.2237, -0.1856, -1.0826, -0.8347,  1.4667])

In [13]:
x.view(-1, 2)

tensor([[-0.7071, -1.2237],
        [-0.1856, -1.0826],
        [-0.8347,  1.4667]])

In [27]:
v = torch.arange(6)
v = v.view(-1, 3)
v

tensor([[0, 1, 2],
        [3, 4, 5]])

In [23]:
vvv = torch.cat([v, v, v], dim=1)

In [19]:
t = torch.ones(2, 1, 2, 1)

In [22]:
t.squeeze(1)

tensor([[[1.],
         [1.]],

        [[1.],
         [1.]]])

In [24]:
vvv.clamp(3, 5)

tensor([[3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 4, 5, 3, 4, 5, 3, 4, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [44]:
v

tensor([[0, 1, 2],
        [3, 4, 5]])

In [50]:
torch.mul(v, v).sum(dim=1)

tensor([ 5, 50])

In [32]:
v.t()

tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [52]:
torch.mul(v, v)

tensor([[ 0,  1,  4],
        [ 9, 16, 25]])

In [51]:
torch.mm(v, v.t())

tensor([[ 5, 14],
        [14, 50]])

In [48]:
torch.dot(torch.Tensor([3, 4, 5]), torch.Tensor([3, 4, 5]))

tensor(50.)

In [77]:
batch1 = torch.randn(10, 3, 4)
batch2 = torch.randn(10, 4)

In [78]:
batch2.unsqueeze(2).shape

torch.Size([10, 4, 1])

In [80]:
torch.bmm(batch1, batch2.unsqueeze(2)).squeeze()

tensor([[-6.0407e-01,  1.0563e+00,  5.1526e+00],
        [-1.8089e+00,  5.6272e-01, -1.2480e+00],
        [-3.4575e+00, -4.3414e-01, -7.6773e-01],
        [ 3.6948e+00,  5.1549e-01,  1.6940e+00],
        [ 8.8007e-01, -1.0703e+00,  6.8491e-01],
        [-2.5483e+00, -2.0009e-01,  3.7187e+00],
        [-1.4256e+00,  7.4298e-01, -4.0857e+00],
        [-2.0934e+00, -1.5163e+00, -7.5562e-01],
        [-3.5043e-01, -6.1580e-01,  8.1407e-04],
        [ 2.0840e+00,  2.1922e-01, -5.3861e-01]])

### Dot product of matrix and vector = sum(matrix * vector)

In [6]:
a = torch.Tensor([[1, 2, 3], [1, 2, 3]]).view(-1, 2)
b = torch.Tensor([[1, 2, 3], [1, 2, 3]]).view(-1, 2)
print(a)
print(a.size())

print(b)
print(b.size())

tensor([[1., 2.],
        [3., 1.],
        [2., 3.]])
torch.Size([3, 2])
tensor([[1., 2.],
        [3., 1.],
        [2., 3.]])
torch.Size([3, 2])


In [9]:
torch.mm(a, b.T)

tensor([[ 5.,  5.,  8.],
        [ 5., 10.,  9.],
        [ 8.,  9., 13.]])

In [14]:
torch.sum(torch.matmul(a, b.T), dim=1)

tensor([18., 24., 30.])

In [13]:
torch.sum(a * b, dim=1)

tensor([ 5., 10., 13.])

In [15]:
a

tensor([[1., 2.],
        [3., 1.],
        [2., 3.]])

In [25]:
b[-1]

tensor([2., 3.])

In [24]:
a.matmul(b[-1].T)

tensor([ 8.,  9., 13.])

In [28]:
torch.sum(a * b[-1], axis=1)

tensor([ 8.,  9., 13.])